#!/bin/bash

pacstrap /mnt base linux linux-firmware vim intel-ucode lvm2

genfstab -U /mnt >> /mnt/etc/fstab
lsblk >> blockid
arch-chroot /mnt

ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
hwclock --systohc
sed -i '177s/.//' /etc/locale.gen
locale-gen
echo "mobile" >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 mobile.localdomain mobile" >> /etc/hosts


# You can add xorg to the installation packages, I usually add it at the DE or WM install script
# You can remove the tlp package if you are installing on a desktop or vm

pacman -S grub efibootmgr networkmanager network-manager-applet wireless_tools wpa_supplicant dialog os-prober mtools dosfstools base-devel linux-headers git reflector bluez bluez-utils pulseaudio-bluetooth cups hplip xdg-utils xdg-users-dirs iptables-nft ipset firewalld openssh tlp acpid


grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
